### ISSUE TITLE
@refetchable directive?

### ISSUE THREAD

**Issue by FezVrasta** [johnsonjo4531/typegraphql-relay-connections#1]
Hi, when I try to use the @refetchable directive, Relay compiler complains with:

```
Error: ✖︎ Invalid use of @refetchable on fragment 'deliveryChannelSelector', only supported are fragments on:
[web-client]: [relay]  - the Viewer type
[web-client]: [relay]  - the Query type
[web-client]: [relay]  - the Node interface, object types that implement the Node interface, interfaces whose implementing objects all implement Node, and unions whose members all implement Node
[web-client]: [relay]  - server objects and interfaces with the @fetchable directive
[web-client]: [relay] 
```

I'm defining my fragment with:

```ts
const [deliveryChannels, refetchDeliveryChannels] = useRefetchableFragment(
    graphql`
      fragment deliveryChannelSelector on CreatorNode
      @refetchable(queryName: "deliveryChannelSelectorRefetchQuery") {
        id
       deliveryChannels {
          __id
          edges {
            node {
              id
              name
            }
          }
        }
      }
    `,
    deliveryChannelsKey,
  );
```

And the schema is using something along the examples provided in this repository.

What am I missing?

**Comment by johnsonjo4531** [comment]
Hey sorry, when you first posted this I was trying to go through the process of creating a minimum reproducible example of this for you, and help you see the solution to the problem from there. Truth is I ran out of time and got busy. I feel bad I neglected this issue. I will instead just explain what you need to do and as long as you still need help I will help you if you have further questions.  Now this issue isn't too that specific to this library, but I'm glad to try and help you here with the time I do have. What you need to do is setup your type returned from deliveryChannels' node to be a Node interface. The Node interface was described in your error message as one of the supported fragment types:

```
Invalid use of @refetchable on fragment 'deliveryChannelSelector', only supported are fragments on:
...
- the Node interface, object types that implement the Node interface, interfaces whose implementing objects all implement Node, and unions whose members all implement Node
...
```

Unspecific to this library what you are after is implementing the [GraphQL Global Object Identification specification](https://relay.dev/graphql/objectidentification.htm). 

The first step is to setup a [Node interface](https://relay.dev/graphql/objectidentification.htm#sec-Node-Interface) Which is detailed there as:

> Node Interface
> The server must provide an interface called Node. That interface must include exactly one field, called id that returns a non-null ID.
> 
> This id should be a globally unique identifier for this object, and given just this id, the server should be able to refetch the object.

In TypeGraphql that means you need to use [TypeGraphQL's interface](https://typegraphql.com/docs/interfaces.html)

So, if we implement the Node interface as described above it would look like:

```ts
/** This is the Node interface from the Global Object Identification spec https://relay.dev/graphql/objectidentification.htm#sec-Node-Interface */
@InterfaceType()
abstract class Node {
  @Field(type => ID)
  id: string;
}
```

Then you must also add the `node(id: ID)` query resolver to the root Query. 

```ts
// Don't forget to include the below resolver in your list of resolvers when building your graphql schema.
@Resolver() 
export class NodeResolvers {
  /** https://relay.dev/graphql/objectidentification.htm#sec-Node-root-field */
  @Query(returns => Node)
  async node(
    @Arg("id") id: ID,
  ): Promise<Node> {
    return // you must do this yourself, because it will depend completely on what database you are using...
  }
}
```


Specific to this library you need to make sure that if you want @refetchable support and you do the following: 

```ts
// This is the EdgeType:
@ObjectType()
export class DeliveryChannelEdge extends EdgeType(DeliveryChannel) {}
```

then you must make sure your `DeliveryChannel` implements the Node Interface as shown previously which in TypeGraphQL would look something like:

```ts
@ObjectType({ implements: Node })
class DeliveryChannel implements Node {
  id: string;
  // the rest of your class....
}
```

All this has not been tested so I may have messed something up, but feel free to at tag me if you need further help and are still stuck. Thanks!

**Comment by johnsonjo4531** [comment]
@FezVrasta sorry forgot to at tag you in the last message just wanted to make sure you saw it though, so I'm at tagging you here. :D

**Comment by FezVrasta** [comment]
Thanks, this worked, I did manage to make it work but forgot to update you here :-( I'm sorry about that.

**Comment by johnsonjo4531** [comment]
No worries!! Glad you got it to work, sorry I wasn't able to help you earlier :)
